const iconBank = [
  { name: "hamburger", family: "FontAwesome5" },
  { name: "hotdog", family: "FontAwesome5" },
  { name: "pizza-slice", family: "FontAwesome5" },
  { name: "food-drumstick", family: "MaterialCommunityIcons" },
  { name: "rice", family: "MaterialCommunityIcons" },
  { name: "noodles", family: "MaterialCommunityIcons" },
  { name: "egg", family: "MaterialCommunityIcons" },
  { name: "sausage", family: "MaterialCommunityIcons" },
  { name: "leaf", family: "FontAwesome5" },
  { name: "bread-slice", family: "FontAwesome5" },
  { name: "bacon", family: "FontAwesome5" },
  { name: "stroopwafel", family: "FontAwesome5" },
  { name: "food-croissant", family: "MaterialCommunityIcons" },
  { name: "cheese", family: "FontAwesome5" },
  { name: "fish", family: "FontAwesome5" },
  { name: "taco", family: "MaterialCommunityIcons" },
  { name: "apple-alt", family: "FontAwesome5" },
  { name: "corn", family: "MaterialCommunityIcons" },
  { name: "carrot", family: "FontAwesome5" },
  { name: "pepper-hot", family: "FontAwesome5" },
  { name: "ice-cream", family: "FontAwesome5" },
  { name: "cookie", family: "FontAwesome5" },
  { name: "fast-food", family: "Ionicons" },
  { name: "md-bonfire", family: "Ionicons" },
  { name: "fireplace", family: "MaterialCommunityIcons" },
  { name: "cocktail", family: "FontAwesome5" },
  { name: "ios-wine", family: "Ionicons" },
  { name: "wine-bottle", family: "FontAwesome5" },
  { name: "beer", family: "FontAwesome5" },
  { name: "coffee", family: "FontAwesome5" },
  { name: "bottle-soda-classic", family: "MaterialCommunityIcons" },
  { name: "seedling", family: "FontAwesome5" },
  { name: "wheelchair", family: "FontAwesome5" },
  { name: "volume-low", family: "Ionicons" },
  { name: "glass-cheers", family: "FontAwesome5" },
  { name: "grin-squint-tears", family: "FontAwesome5" },
  { name: "book-open-page-variant", family: "MaterialCommunityIcons" },
  { name: "hiking", family: "FontAwesome5" },
  { name: "baby-carriage", family: "FontAwesome5" },
  { name: "car", family: "FontAwesome5" },
  { name: "cart-plus", family: "FontAwesome5" },
  { name: "handshake", family: "FontAwesome5" },
];

export default iconBank;
