const iconBank = [
  { name: "hamburger", family: "font-awesome-5", feature: "Hambugers" },
  { name: "hotdog", family: "font-awesome-5", feature: "Hotdogs" },
  { name: "pizza-slice", family: "font-awesome-5", feature: "Pizza" },
  { name: "food-drumstick", family: "material-community", feature: "Chicken" },
  { name: "rice", family: "material-community", feature: "Asian Cuisine" },
  { name: "noodles", family: "material-community", feature: "Noodles" },
  { name: "egg", family: "material-community", feature: "Eggs" },
  { name: "sausage", family: "material-community", feature: "Sausages" },
  { name: "leaf", family: "font-awesome-5", feature: "Vegan" },
  { name: "bread-slice", family: "font-awesome-5", feature: "Bread" },
  { name: "bacon", family: "font-awesome-5", feature: "Bacon" },
  { name: "stroopwafel", family: "font-awesome-5", feature: "Waffles" },
  { name: "food-croissant", family: "material-community", feature: "Croissants" },
  { name: "cheese", family: "font-awesome-5", feature: "Cheese" },
  { name: "fish", family: "font-awesome-5", feature: "Fish" },
  { name: "taco", family: "material-community", feature: "Tacos" },
  { name: "apple-alt", family: "font-awesome-5", feature: "Apple" },
  { name: "corn", family: "material-community", feature: "Corn" },
  { name: "carrot", family: "font-awesome-5", feature: "Carrot" },
  { name: "pepper-hot", family: "font-awesome-5", feature: "Spicy" },
  { name: "ice-cream", family: "font-awesome-5", feature: "Ice Cream" },
  { name: "cookie", family: "font-awesome-5", feature: "Cookie" },
  { name: "fast-food", family: "ionicon", feature: "Fast Food" },
  { name: "md-bonfire", family: "ionicon", feature: "Campfire" },
  { name: "fireplace", family: "material-community", feature: "Warm" },
  { name: "cocktail", family: "font-awesome-5", feature: "Cocktails" },
  { name: "ios-wine", family: "ionicon", feature: "Wine" },
  { name: "wine-bottle", family: "font-awesome-5", feature: "Wine Bottles" },
  { name: "beer", family: "font-awesome-5", feature: "Beer" },
  { name: "coffee", family: "font-awesome-5", feature: "Coffee" },
  { name: "bottle-soda-classic", family: "material-community", feature: "Sodas" },
  { name: "seedling", family: "font-awesome-5", feature: "Hambugers" },
  { name: "wheelchair", family: "font-awesome-5", feature: "Hambugers" },
  { name: "volume-low", family: "ionicon", feature: "Quiet" },
  { name: "glass-cheers", family: "font-awesome-5", feature: "Bar" },
  { name: "grin-squint-tears", family: "font-awesome-5", feature: "Social" },
  { name: "book-open-page-variant", family: "material-community", feature: "Study Space" },
  { name: "hiking", family: "font-awesome-5", feature: "Travelling Stop" },
  { name: "baby-carriage", family: "font-awesome-5", feature: "Toddler Friendly" },
  { name: "car", family: "font-awesome-5", feature: "Drive Through" },
  { name: "cart-plus", family: "font-awesome-5", feature: "Grocery" },
  { name: "handshake", family: "font-awesome-5", feature: "Buisness Friendly" },
];

export default iconBank;
